version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql-data:/var/lib/mysql
    ports:
      - "7000:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./phpmyadmin-data:/sessions
    ports:
      - "8080:80"

  webserver:
    image: php:7.3-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    links:
      - db
